import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [{ path: '', loadChildren: () => import('./home/home.module').then(m => m.HomeModule) }, { path: 'job-list', loadChildren: () => import('./job-list/job-list.module').then(m => m.JobListModule) }, { path: 'about', loadChildren: () => import('./about/about.module').then(m => m.AboutModule) }, { path: 'job-job-details', loadChildren: () => import('./job-details/job-details.module').then(m => m.JobDetailsModule) }, { path: 'candidates', loadChildren: () => import('./candidates/candidates.module').then(m => m.CandidatesModule) }, { path: 'candidate-profile', loadChildren: () => import('./candidate-profile/candidate-profile.module').then(m => m.CandidateProfileModule) }, { path: 'companies', loadChildren: () => import('./companies/companies.module').then(m => m.CompaniesModule) }, { path: 'company-details', loadChildren: () => import('./company-details/company-details.module').then(m => m.CompanyDetailsModule) }, { path: 'login', loadChildren: () => import('./login/login.module').then(m => m.LoginModule) }, { path: 'register', loadChildren: () => import('./register/register.module').then(m => m.RegisterModule) }, { path: 'post-job', loadChildren: () => import('./post-job/post-job.module').then(m => m.PostJobModule) }, { path: 'post-test', loadChildren: () => import('./post-test/post-test.module').then(m => m.PostTestModule) }, { path: 'contact', loadChildren: () => import('./contact/contact.module').then(m => m.ContactModule) }, { path: 'my-profile', loadChildren: () => import('./my-profile/my-profile.module').then(m => m.MyProfileModule) }, { path: 'forgot-password', loadChildren: () => import('./forgot-password/forgot-password.module').then(m => m.ForgotPasswordModule) }, { path: 'reset-password', loadChildren: () => import('./reset-password/reset-password.module').then(m => m.ResetPasswordModule) }, { path: 'manage-jobs', loadChildren: () => import('./manage-jobs/manage-jobs.module').then(m => m.ManageJobsModule) }, { path: 'application', loadChildren: () => import('./application/application.module').then(m => m.ApplicationModule) }, { path: 'test', loadChildren: () => import('./test/test.module').then(m => m.TestModule) }, { path: 'searchJobs', loadChildren: () => import('./search-jobs/search-jobs.module').then(m => m.SearchJobsModule) }];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
